const mazeMap1 = { //LRTB
  0: [true, false, true, true],
  1: [false, false, true, true],
  2: [false, false, true, true],
  3: [false, true,true, false],
  4: [true, true, true, false],
  5: [true, false, false, false],
  6: [false, false, false, true],
  7: [false, true, false, false],
  8: [true, false, false, true],
  9: [false, true, false, false],
  10: [true, false, false, true],
  11: [false, true, true, false],
  12: [true, false, false, true],
  13: [false, true, true, false],
  14: [true, true, false, false],
  15: [true, false, true, false],
  16: [false, true, false, false],
  17: [true, false, true, true],
  18: [false, true, false, false],
  19: [true, true, false, false],
  20: [true, true, false, true],
  21: [true, false, false, true],
  22: [false, true, true, true],
  23: [true, false, false, true],
  24: [false, true, false, true],
};
const start1=0;
const end1=22;